encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:page>/", views.page, name='page'),
    path("search/", views.search, name='search'),
    path("random/", views.random, name='random'),
    path("new_page/", views.new_page, name='new_page'),
    path("wiki/<str:pageHead>/edit/", views.edit_page, name='edit_page')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from faulthandler import disable
from hashlib import new
from logging import PlaceHolder
from multiprocessing import context
from tkinter import DISABLED
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from markdown2 import Markdown
from django import forms
from django.urls import reverse
from random import choice

from . import util

class NewPageForm(forms.Form):
    pageHead = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Заголовок сторінки.'}
    ))
    pageBody = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Текст сторінки.'}
    ))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "pages": util.list_entries()
    })



def page(request, page):
    markdownpage = Markdown()
    pageEntry = util.get_entry(page)
    if pageEntry is None:
        return render (request, "encyclopedia/fileNoneExist.html", {
        "pageHead": page
    })  
    else:
        return render (request,"encyclopedia/page.html", {
        "page": markdownpage.convert(pageEntry),
        "pageHead": page
    })



def search(request):
    search_page = request.GET.get("q")
    search_list = []
    if util.get_entry(search_page) is not None:
        return HttpResponseRedirect(reverse("encyclopedia:page", kwargs={"page": search_page}))
    else:
        search_page_lower = search_page.lower()
        entries = util.list_entries()
        for entry in entries:
           search_cycle = entry.lower().find(search_page_lower)
           if search_cycle != -1: 
              search_list.append(entry)
              print(search_list)
        if len(search_list)==0:
            return render (request, "encyclopedia/fileNoneExist.html", {
                "pageHead": search_page
        })
        else:
             return render (request, "encyclopedia/search_result.html", {
                "pages": search_list
        })


def random(request):
    pages = util.list_entries()
    page = choice(pages)
    return HttpResponseRedirect(reverse("encyclopedia:page", kwargs={'page': page})) 





def new_page(request):
    markdownpage = Markdown()
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
           pageHead=form.cleaned_data['pageHead']
           pageBody=form.cleaned_data['pageBody']
           if pageHead in util.list_entries():
                error = "This page is exist. You can find it and change."
                return render(request, "encyclopedia/new_page.html", {
                    "form": form,
                    "error": error,
                    "edit": False
                })
           else: 
               util.save_entry(pageHead, pageBody)
               return render (request,"encyclopedia/page.html", {
                    "page": markdownpage.convert(pageBody),
                    "pageHead": pageHead
               })
    return render(request, "encyclopedia/new_page.html", {
        "form": NewPageForm() 
    })



def edit_page(request, pageHead):
    pageBody =util.get_entry(pageHead) 
    form = NewPageForm()
    form.fields['pageHead'].initial = pageHead
    form.fields['pageBody'].initial = pageBody
    form.fields['pageHead'].widget = forms.HiddenInput()
    if request.method == "POST":
        pageHead = request.POST['pageHead']
        pageBody = request.POST['pageBody']
        util.save_entry(pageHead, pageBody)
        return HttpResponseRedirect(reverse("encyclopedia:page", kwargs={'page': pageHead}))
    return render (request,"encyclopedia/new_page.html", {
                "form": form,
                "edit": True,
                "pageHead": form.fields['pageHead'].initial
    })

encyclopedia/templates/encyclopedia/fileNoneExist.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ pageHead }}
{% endblock %}

{% block body %}
    <h1 style="color: white; text-align: center;">{{ pageHead }}</h1>
    <p style="color: white; text-align: center;">This page is not exist. You can create it. Push "Нова стаття".</p>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div class="center">
        <h1 style="color:white; -webkit-text-stroke: 2px black; font-size: 60px;">All Pages</h1>
    </div>


    <div class="centerTable">
    {% for page in pages %}
        <a href="/wiki/{{ page|safe }}" class="elementList" >{{page}}</a>
        <br/>
    {% endfor %}
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3" style="background-color: rgb(6, 22, 37); text-align: center;">
                <h1 class="menulink">Wikipedia</h1>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class = "search" type = "text" name = "q" placeholder="Search text">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}" class="menulink" style="font-size: 30px;">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}" class="menulink" style="font-size: 30px;">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}" class="menulink" style="font-size: 30px;">Random page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   Create new page
{% endblock %}

{% block body %}
   {% if edit %}
     <h1 style="color:white; font-size: 60px; text-align: center;">Edit page: {{pageHead}}</h1>
     <form method="post"  style="text-align: center;">
       {% csrf_token %}
       {{form.pageHead}}<br>
       <label for="Page text:">Page text:</label>
       {{form.pageBody}}<br>
       <button type="submit" class="button">Edit page</button>
    </form>
   {% else %}
    <h1 style="color:white; font-size: 60px; text-align: center;">Create new page</h1>
    <form method="post" style="text-align: center;">
        {% csrf_token %}
        <label for="Page title:" style="color:white; font-size: 24px;">Page title:</label>
        {{form.pageHead}}<br>
        <label for="Page text:" style="color:white; font-size: 24px;">Page text:</label>
        {{form.pageBody}}<br>
        <span>{{error}}</span><br>
        <button class="btn btn-success" type="submit">Save page</button>
    </form>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ pageHead }}
{% endblock %}




{% block body %}
<div class="centerTable"></div>
<form action="{% url 'encyclopedia:edit_page' pageHead %}">
    <header>
        <button class="button" type="submit" method="get">Edit page</button>
    </header>
    <div style="color: white; text-align: center; font-size: 32px;">
        <a>{{page|safe}}</a>
            <input type="hidden" value="{{pageHead}}" name="pageHead">
        </form>
    </div>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/search_result.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   Search result
{% endblock %}

{% block body %}
    <h1>Search result</h1>

    <ul>
        {% for page in pages %}
            <a href="/wiki/{{page}}"><li>{{page}}</li></a>
        {% endfor %}
    </ul>

{% endblock %}